// ── Menu Categories (Dal Bhaffle branded — 4 main + All) ─────────────────
export const MENU_CATEGORIES = [
  { id: 'all',    name: 'All',     icon: '🍽️',  category: null },
  { id: 'dal',    name: 'Dal',     icon: '🫕',  category: 'Dal' },
  { id: 'bhaffle',name: 'Bhaffle', icon: '🫓',  category: 'Bhaffle' },
  { id: 'drinks', name: 'Drinks',  icon: '🥤',  category: 'Drinks' },
  { id: 'combos', name: 'Combos',  icon: '🎁',  category: 'Combos' },
  { id: 'sweets', name: 'Sweets',  icon: '🍮',  category: 'Sweets' },
  { id: 'extras', name: 'Extras',  icon: '🧆',  category: 'Extras' },
];

// ── Hero Category Cards (shown on home screen as big tap tiles) ───────────
export const HOME_CATEGORIES = [
  {
    id: 'dal',
    name: 'Dal',
    tagline: 'Rich & Flavourful',
    emoji: '🫕',
    gradient: ['#C8420F', '#E8793A'] as const,
    badge: 'Pure Desi',
    category: 'Dal',
  },
  {
    id: 'bhaffle',
    name: 'Bhaffle',
    tagline: 'Crispy Baked Goodness',
    emoji: '🫓',
    gradient: ['#8B5E3C', '#C4935E'] as const,
    badge: 'Chef's Special',
    category: 'Bhaffle',
  },
  {
    id: 'drinks',
    name: 'Drinks',
    tagline: 'Refresh & Unwind',
    emoji: '🥤',
    gradient: ['#1A7D4A', '#2EAA6B'] as const,
    badge: 'Chilled Fresh',
    category: 'Drinks',
  },
  {
    id: 'combos',
    name: 'Combos',
    tagline: 'Best Value Bundles',
    emoji: '🎁',
    gradient: ['#5A3FC0', '#9B6BF0'] as const,
    badge: 'Save More',
    category: 'Combos',
  },
];

// ── Menu Items ────────────────────────────────────────────────────────────
export const MENU_ITEMS = [
  {
    id: '1',
    name: 'Dal Tadka',
    description: 'Slow-cooked masoor dal tempered with ghee, cumin & garlic — served with bafla',
    price: 120,
    originalPrice: 150,
    image: 'https://picsum.photos/seed/daltadka1/400/300',
    category: 'Dal',
    isVeg: true,
    isBestseller: true,
    rating: 4.8,
    prepTime: '20 min',
    calories: 320,
    addons: [
      { id: 'a1', name: 'Extra Ghee', price: 20 },
      { id: 'a2', name: 'Extra Dal', price: 30 },
      { id: 'a3', name: 'Spicy (Level 1–3)', price: 0 },
    ],
  },
  {
    id: '2',
    name: 'Panchmel Dal',
    description: 'Five-lentil blend cooked with whole spices — the Rajasthani classic',
    price: 140,
    originalPrice: 170,
    image: 'https://picsum.photos/seed/panchmel1/400/300',
    category: 'Dal',
    isVeg: true,
    isBestseller: false,
    rating: 4.6,
    prepTime: '25 min',
    calories: 380,
    addons: [
      { id: 'a1', name: 'Extra Ghee', price: 20 },
      { id: 'a2', name: 'Extra Dal', price: 30 },
    ],
  },
  {
    id: '3',
    name: 'Bhaffle Regular (3pc)',
    description: 'Traditional Bhopal-style baked wheat dumplings dipped in pure ghee',
    price: 100,
    originalPrice: 130,
    image: 'https://picsum.photos/seed/bhaffle1/400/300',
    category: 'Bhaffle',
    isVeg: true,
    isBestseller: true,
    rating: 4.9,
    prepTime: '20 min',
    calories: 450,
    addons: [
      { id: 'a1', name: 'Extra Ghee', price: 20 },
      { id: 'a3', name: 'Churma', price: 40 },
    ],
  },
  {
    id: '4',
    name: 'Bhaffle Jumbo (6pc)',
    description: 'Double serving of crispy bafla with extra churma and desi ghee',
    price: 180,
    originalPrice: 220,
    image: 'https://picsum.photos/seed/bhaffle2/400/300',
    category: 'Bhaffle',
    isVeg: true,
    isBestseller: true,
    rating: 4.8,
    prepTime: '30 min',
    calories: 850,
    addons: [
      { id: 'a1', name: 'Extra Ghee', price: 20 },
      { id: 'a3', name: 'Churma', price: 40 },
      { id: 'a4', name: 'Extra Baati (2pc)', price: 30 },
    ],
  },
  {
    id: '5',
    name: 'Dal Bhaffle Combo',
    description: 'Dal Tadka + 3 Bhaffle + Churma + Ghee — the full experience',
    price: 199,
    originalPrice: 260,
    image: 'https://picsum.photos/seed/combo1/400/300',
    category: 'Combos',
    isVeg: true,
    isBestseller: true,
    rating: 4.9,
    prepTime: '25 min',
    calories: 720,
    addons: [
      { id: 'a1', name: 'Extra Ghee', price: 20 },
      { id: 'a5', name: 'Lassi Add-on', price: 50 },
    ],
  },
  {
    id: '6',
    name: 'Family Feast Combo',
    description: 'Serves 4 — Panchmel Dal, 10 Bhaffle, Churma, Sabzi, Achar & Papad',
    price: 399,
    originalPrice: 480,
    image: 'https://picsum.photos/seed/combo2/400/300',
    category: 'Combos',
    isVeg: true,
    isBestseller: true,
    rating: 4.8,
    prepTime: '40 min',
    calories: 2200,
    addons: [
      { id: 'a3', name: 'Extra Churma', price: 60 },
      { id: 'a6', name: 'Sweet (Gulab Jamun 4pc)', price: 50 },
    ],
  },
  {
    id: '7',
    name: 'Sweet Lassi',
    description: 'Chilled thick sweet lassi — the perfect companion for Dal Bhaffle',
    price: 50,
    originalPrice: 65,
    image: 'https://picsum.photos/seed/lassi1/400/300',
    category: 'Drinks',
    isVeg: true,
    isBestseller: false,
    rating: 4.5,
    prepTime: '5 min',
    calories: 200,
    addons: [],
  },
  {
    id: '8',
    name: 'Salted Lassi',
    description: 'Refreshing salted lassi with roasted cumin and fresh mint',
    price: 50,
    originalPrice: 65,
    image: 'https://picsum.photos/seed/lassi2/400/300',
    category: 'Drinks',
    isVeg: true,
    isBestseller: false,
    rating: 4.3,
    prepTime: '5 min',
    calories: 150,
    addons: [],
  },
  {
    id: '9',
    name: 'Masala Chaas',
    description: 'Spiced buttermilk with ginger, coriander, and a pinch of hing',
    price: 40,
    originalPrice: 55,
    image: 'https://picsum.photos/seed/chaas1/400/300',
    category: 'Drinks',
    isVeg: true,
    isBestseller: true,
    rating: 4.6,
    prepTime: '3 min',
    calories: 80,
    addons: [],
  },
  {
    id: '10',
    name: 'Churma Ladoo (4pc)',
    description: 'Sweet wheat flour balls made with ghee and jaggery',
    price: 60,
    originalPrice: 80,
    image: 'https://picsum.photos/seed/churma1/400/300',
    category: 'Extras',
    isVeg: true,
    isBestseller: false,
    rating: 4.6,
    prepTime: '10 min',
    calories: 320,
    addons: [],
  },
];

// ── Offers ────────────────────────────────────────────────────────────────
export const OFFERS = [
  {
    id: 'o1',
    title: 'First Order Special',
    subtitle: 'Get ₹50 OFF on your first order',
    code: 'FIRST50',
    color: '#FF6B00',
  },
  {
    id: 'o2',
    title: 'Family Feast Deal',
    subtitle: 'Order Family Combo & get free Lassi',
    code: 'FAMILY',
    color: '#43A047',
  },
  {
    id: 'o3',
    title: 'Weekend Special',
    subtitle: '20% OFF on all Combos — Sat & Sun only',
    code: 'WEEKEND20',
    color: '#1E88E5',
  },
];

// ── Order statuses ─────────────────────────────────────────────────────────
export const ORDER_STATUSES = [
  { key: 'placed',           label: 'Order Placed',      icon: 'receipt-outline',         description: 'Your order has been received' },
  { key: 'accepted',         label: 'Accepted',          icon: 'checkmark-circle-outline', description: 'Kitchen has accepted your order' },
  { key: 'preparing',        label: 'Preparing',         icon: 'flame-outline',            description: 'Your food is being prepared' },
  { key: 'out_for_delivery', label: 'Out for Delivery',  icon: 'bicycle-outline',          description: 'On the way to you!' },
  { key: 'delivered',        label: 'Delivered',         icon: 'home-outline',             description: 'Enjoy your meal!' },
];

// ── Coupon seed data ───────────────────────────────────────────────────────
export const COUPONS: Record<string, number> = {
  FIRST50:   50,
  FAMILY:    0,
  WEEKEND20: 0,
  SAVE30:    30,
  DALBHAFFLE: 40,
};
