export const MENU_CATEGORIES = [
  { id: '1', name: 'All', icon: '🍽️' },
  { id: '2', name: 'Dal Bafla', icon: '🫕' },
  { id: '3', name: 'Thali', icon: '🍛' },
  { id: '4', name: 'Extras', icon: '🧆' },
  { id: '5', name: 'Sweets', icon: '🍮' },
  { id: '6', name: 'Drinks', icon: '🥤' },
];

export const MENU_ITEMS = [
  {
    id: '1',
    name: 'Dal Bafla Regular',
    description: 'Traditional Bhopal-style baked wheat dumplings served with dal and ghee',
    price: 120,
    originalPrice: 150,
    image: 'https://picsum.photos/seed/dalbafla1/400/300',
    category: 'Dal Bafla',
    isVeg: true,
    isBestseller: true,
    rating: 4.8,
    prepTime: '20 min',
    calories: 450,
    addons: [
      { id: 'a1', name: 'Extra Ghee', price: 20 },
      { id: 'a2', name: 'Extra Dal', price: 30 },
      { id: 'a3', name: 'Churma', price: 40 },
    ],
  },
  {
    id: '2',
    name: 'Dal Bafla Mini',
    description: 'Smaller portion of classic Dal Bafla — great for light hunger',
    price: 80,
    originalPrice: 100,
    image: 'https://picsum.photos/seed/dalbafla2/400/300',
    category: 'Dal Bafla',
    isVeg: true,
    isBestseller: false,
    rating: 4.5,
    prepTime: '15 min',
    calories: 280,
    addons: [
      { id: 'a1', name: 'Extra Ghee', price: 20 },
      { id: 'a2', name: 'Extra Dal', price: 30 },
    ],
  },
  {
    id: '3',
    name: 'Dal Bafla Family Pack',
    description: 'Serves 4 — Dal Bafla with churma, baati, ghee, and achar',
    price: 380,
    originalPrice: 450,
    image: 'https://picsum.photos/seed/dalbafla3/400/300',
    category: 'Dal Bafla',
    isVeg: true,
    isBestseller: true,
    rating: 4.9,
    prepTime: '35 min',
    calories: 1600,
    addons: [
      { id: 'a3', name: 'Extra Churma', price: 60 },
      { id: 'a4', name: 'Extra Baati (4pc)', price: 50 },
    ],
  },
  {
    id: '4',
    name: 'Full Thali',
    description: 'Dal, Bafla, Churma, Sabzi, Roti, Rice, Papad, Achar & Dessert',
    price: 180,
    originalPrice: 220,
    image: 'https://picsum.photos/seed/thali1/400/300',
    category: 'Thali',
    isVeg: true,
    isBestseller: true,
    rating: 4.7,
    prepTime: '25 min',
    calories: 750,
    addons: [
      { id: 'a5', name: 'Extra Roti (2pc)', price: 20 },
      { id: 'a6', name: 'Sweet (Gulab Jamun)', price: 30 },
    ],
  },
  {
    id: '5',
    name: 'Mini Thali',
    description: 'Dal, 2 Bafla, Sabzi, Roti & Achar — light and satisfying',
    price: 120,
    originalPrice: 150,
    image: 'https://picsum.photos/seed/thali2/400/300',
    category: 'Thali',
    isVeg: true,
    isBestseller: false,
    rating: 4.4,
    prepTime: '20 min',
    calories: 520,
    addons: [],
  },
  {
    id: '6',
    name: 'Churma Ladoo (4pc)',
    description: 'Sweet wheat flour balls made with ghee and jaggery',
    price: 60,
    originalPrice: 80,
    image: 'https://picsum.photos/seed/churma1/400/300',
    category: 'Sweets',
    isVeg: true,
    isBestseller: false,
    rating: 4.6,
    prepTime: '10 min',
    calories: 320,
    addons: [],
  },
  {
    id: '7',
    name: 'Baati (6pc)',
    description: 'Crispy baked wheat dumplings served with ghee',
    price: 70,
    originalPrice: 90,
    image: 'https://picsum.photos/seed/baati1/400/300',
    category: 'Extras',
    isVeg: true,
    isBestseller: false,
    rating: 4.5,
    prepTime: '15 min',
    calories: 380,
    addons: [
      { id: 'a1', name: 'Extra Ghee', price: 20 },
    ],
  },
  {
    id: '8',
    name: 'Lassi (Sweet)',
    description: 'Chilled sweet lassi — the perfect companion for Dal Bafla',
    price: 50,
    originalPrice: 60,
    image: 'https://picsum.photos/seed/lassi1/400/300',
    category: 'Drinks',
    isVeg: true,
    isBestseller: false,
    rating: 4.3,
    prepTime: '5 min',
    calories: 180,
    addons: [],
  },
];

export const OFFERS = [
  {
    id: 'o1',
    title: 'First Order Special',
    subtitle: 'Get ₹50 OFF on your first order',
    code: 'FIRST50',
    color: '#FF6B00',
  },
  {
    id: 'o2',
    title: 'Family Pack Deal',
    subtitle: 'Order Family Pack & get free Lassi',
    code: 'FAMILY',
    color: '#43A047',
  },
  {
    id: 'o3',
    title: 'Weekend Thali',
    subtitle: '20% OFF on Full Thali — Sat & Sun only',
    code: 'WEEKEND20',
    color: '#1E88E5',
  },
];

export const ORDER_STATUSES = [
  { key: 'placed', label: 'Order Placed', icon: 'receipt-outline', description: 'Your order has been received' },
  { key: 'accepted', label: 'Accepted', icon: 'checkmark-circle-outline', description: 'Kitchen has accepted your order' },
  { key: 'preparing', label: 'Preparing', icon: 'flame-outline', description: 'Your food is being prepared' },
  { key: 'out_for_delivery', label: 'Out for Delivery', icon: 'bicycle-outline', description: 'On the way to you!' },
  { key: 'delivered', label: 'Delivered', icon: 'home-outline', description: 'Enjoy your meal!' },
];

export const COUPONS: Record<string, number> = {
  FIRST50: 50,
  FAMILY: 0,
  WEEKEND20: 0,
  SAVE30: 30,
};
